Ahorasi/Models/Usuarios.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ahorasi.Models
{
    public class Usuarios
    {
        public string Nombres { set; get; }
        public string Correo { set; get; }
        public string Clave { set; get; }
        public Rol IdRol { set; get; }
        
    }
}

Ahorasi/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Ahorasi.Permisos;

using Ahorasi.BD;



namespace Ahorasi.Controllers
{
    [Authorize]
    public class UsuariosController : Controller
    {
        private UsuariosEntities db = new UsuariosEntities();

        // GET: Usuarios

        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Index()
        {
            return View(db.Usuarios.ToList());
        }

        // GET: Usuarios/Details/5

        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios usuarios = db.Usuarios.Find(id);
            if (usuarios == null)
            {
                return HttpNotFound();
            }
            return View(usuarios);
        }

        // GET: Usuarios/Create
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Create([Bind(Include = "Id_Usuario,Nombres,Apellidos,TipoUsuario,Telefono,TipoDocumento,NumeroDocumento")] Usuarios usuarios)
        {
            if (ModelState.IsValid)
            {
                db.Usuarios.Add(usuarios);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(usuarios);
        }

        // GET: Usuarios/Edit/5
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios usuarios = db.Usuarios.Find(id);
            if (usuarios == null)
            {
                return HttpNotFound();
            }
            return View(usuarios);
        }

        // POST: Usuarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Edit([Bind(Include = "Id_Usuario,Nombres,Apellidos,TipoUsuario,Telefono,TipoDocumento,NumeroDocumento")] Usuarios usuarios)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuarios).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usuarios);
        }

        // GET: Usuarios/Delete/5
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios usuarios = db.Usuarios.Find(id);
            if (usuarios == null)
            {
                return HttpNotFound();
            }
            return View(usuarios);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuarios usuarios = db.Usuarios.Find(id);
            db.Usuarios.Remove(usuarios);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ahorasi/Controllers/VehiculosRsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ahorasi.BD;
using Ahorasi.Permisos;

namespace Ahorasi.Controllers
{
    public class VehiculosRsController : Controller
    {
        private UsuariosEntities db = new UsuariosEntities();

        // GET: VehiculosRs

        public ActionResult Index()
        {
            var vehiculosR = db.VehiculosR.Include(v => v.Usuarios);
            return View(vehiculosR.ToList());
        }

        // GET: VehiculosRs/Details/5
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehiculosR vehiculosR = db.VehiculosR.Find(id);
            if (vehiculosR == null)
            {
                return HttpNotFound();
            }
            return View(vehiculosR);
        }

        // GET: VehiculosRs/Create
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Create()
        {
            ViewBag.Id_Usuario = new SelectList(db.Usuarios, "Id_Usuario", "Nombres");
            return View();
        }

        // POST: VehiculosRs/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Create([Bind(Include = "Id_Vehiculo,Fecha,TipoVehiculo,Color,Placa,Marca,Id_Usuario")] VehiculosR vehiculosR)
        {
            if (ModelState.IsValid)
            {
                db.VehiculosR.Add(vehiculosR);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id_Usuario = new SelectList(db.Usuarios, "Id_Usuario", "Nombres", vehiculosR.Id_Usuario);
            return View(vehiculosR);
        }

        // GET: VehiculosRs/Edit/5
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehiculosR vehiculosR = db.VehiculosR.Find(id);
            if (vehiculosR == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_Usuario = new SelectList(db.Usuarios, "Id_Usuario", "Nombres", vehiculosR.Id_Usuario);
            return View(vehiculosR);
        }

        // POST: VehiculosRs/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Edit([Bind(Include = "Id_Vehiculo,Fecha,TipoVehiculo,Color,Placa,Marca,Id_Usuario")] VehiculosR vehiculosR)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehiculosR).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_Usuario = new SelectList(db.Usuarios, "Id_Usuario", "Nombres", vehiculosR.Id_Usuario);
            return View(vehiculosR);
        }

        // GET: VehiculosRs/Delete/5
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehiculosR vehiculosR = db.VehiculosR.Find(id);
            if (vehiculosR == null)
            {
                return HttpNotFound();
            }
            return View(vehiculosR);
        }

        // POST: VehiculosRs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [PermisosRol(Models.Rol.Seguridad)]
        public ActionResult DeleteConfirmed(int id)
        {
            VehiculosR vehiculosR = db.VehiculosR.Find(id);
            db.VehiculosR.Remove(vehiculosR);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ahorasi/Views/Usuarios/Create.cshtml
@model Ahorasi.BD.Usuarios

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/Estilos/StyleSheet4.css" />




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="todo">
    <div class="info">
        <h2>Create User</h2>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control" name="TipoUsuario">
                    <option>Seleccione..</option>
                    <option>Estudiante</option>
                    <option>Profesor</option>
                    <option>Administradores</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control" name="TipoDocumento">
                    <option>Seleccione..</option>
                    <option>Cedula de ciudadania</option>
                    <option>Cedula de extrangeria</option>
                    <option>Tarjeta de identidad</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroDocumento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroDocumento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <a href="@Url.Action("Create","VehiculosRs")"></a>
            </div>
            <button>@Html.ActionLink("Back to List", "Index")</button>
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ahorasi/Views/Usuarios/Delete.cshtml
@model Ahorasi.BD.Usuarios

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/Estilos/StyleSheet7.css" />

<div class="todo">
    <div class="info">
        <h2>Delete</h2>

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Usuarios</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nombres)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombres)
                </dd>
                
                <dt>
                    @Html.DisplayNameFor(model => model.Apellidos)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Apellidos)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TipoUsuario)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TipoUsuario)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Telefono)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Telefono)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TipoDocumento)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TipoDocumento)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.NumeroDocumento)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NumeroDocumento)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    <button>@Html.ActionLink("Back to List", "Index")</button>
                </div>
            }
        </div>
        </div>
</div>

Ahorasi/Views/Usuarios/Details.cshtml
@model Ahorasi.BD.Usuarios

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/Estilos/StyleSheet7.css" />

<div class="todo">
    <div class="info">
        <h2>Details</h2>
        <div>
            <h4>Usuarios</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nombres)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombres)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Apellidos)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Apellidos)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TipoUsuario)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TipoUsuario)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Telefono)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Telefono)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TipoDocumento)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TipoDocumento)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.NumeroDocumento)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NumeroDocumento)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id_Usuario }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
</div>

Ahorasi/Views/Usuarios/Edit.cshtml
@model Ahorasi.BD.Usuarios

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/Estilos/StyleSheet7.css" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="todo">
    <div class="info">
        <h2>Edit</h2>
        <div class="form-horizontal">
            <h4>Usuarios</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id_Usuario)

            <div class="form-group">
                @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TipoUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TipoUsuario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TipoUsuario, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TipoDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TipoDocumento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TipoDocumento, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NumeroDocumento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NumeroDocumento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NumeroDocumento, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
                <button>@Html.ActionLink("Back to List", "Index")</button>
            </div>
        </div>
        </div>
    </div>
        }

       
           
       

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

Ahorasi/Views/Usuarios/Index.cshtml
@model IEnumerable<Ahorasi.BD.Usuarios>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/Estilos/StyleSheet6.css" />

<div class="contan">
    
    <div class="contai">
        <div class="table_header">
            <h2>User    </h2>
            <button>@Html.ActionLink("Create New", "Create")</button>
            <div class="input_search">
                <input type="search" placeholder="Buscar" />
                <i class="bi bi-search" id="search"></i>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Nombres)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Apellidos)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TipoUsuario)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Telefono)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TipoDocumento)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NumeroDocumento)
                    </th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tbody>
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombres)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Apellidos)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TipoUsuario)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Telefono)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TipoDocumento)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NumeroDocumento)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id_Usuario }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Id_Usuario }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id_Usuario })
                        </td>
                    </tr>
                </tbody>
            }
        </table>
        <hr>
    </div>
</div>



<script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>