Ahorasi/Controllers/AccesoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Ahorasi.Models;
using Ahorasi.Logica;
using System.Web.Security;

namespace Ahorasi.Controllers
{
    public class AccesoController : Controller
    {
        // GET: Acceso
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string correo,string clave)
        {
            Usuarios objeto = new LO_Usuario().EncontrarUsuario(correo,clave);

            if (objeto.Nombres !=null)
            {
                FormsAuthentication.SetAuthCookie(objeto.Correo, false);

                Session["Usuario"]=objeto;

                return RedirectToAction("Index","Home");

            }

            return View();
        }


    }
}

Ahorasi/Views/Acceso/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Index</title>
    <link rel="stylesheet" href="~/Estilos/StyleSheet2.css" />
    @Styles.Render("~/Content/css")
</head>
<body>       
                <div class="login-box">
                    <img src="~/Estilos/avatar.jpg" class="avatar"  />
                    <h1>Login </h1>
                    <form action="@Url.Action("Index","Acceso")" method="post">
                        
                            <p>Email</p>
                            <input class="form-control" type="email" name="correo" />                                               
                            <p>Password</p>
                            <input class="form-control" type="password" name="clave" />                       
                        <input type="submit" name="submit" value="Login" />
                    </form>

                    <p>Cuentas para ingresar</p>
                    <h9>tlopza@gmail.com -- 123 -- Administrador</h9>
                    <h9>dgarayf@gmail.com -- 456 -- Seguridad</h9>
                    <h9>cgarayb@gmail.com -- 789 -- Estudiante</h9>
                </div>    
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

Ahorasi/Views/Acceso/Registro.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Registro</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>